-- Carte d'A Piaghja : produits éditables depuis le back-office
CREATE TABLE IF NOT EXISTS carte (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  panel INTEGER NOT NULL,
  categorie TEXT NOT NULL,
  nom TEXT NOT NULL,
  descr TEXT,
  prix TEXT NOT NULL,
  ordre INTEGER NOT NULL,
  visible INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_carte_panel ON carte (panel, ordre);
DELETE FROM carte;
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les incontournables', 'Pina Colada', 'Rhum brun, purée de coco, jus d''ananas, citron vert', '13 €', 1, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les incontournables', 'Margarita', 'Tequila, triple sec, jus de citron, sucre de canne', '12 €', 2, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les incontournables', 'Bloody Mary', 'Vodka, jus de tomate, jus de citron, Worcestershire sauce, tabasco, céleri', '14 €', 3, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les incontournables', 'Negron''Isula', 'Cap Corse Mattei blanc, Martini blanc, Gin Mattei', '16 €', 4, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les incontournables', 'Maï Taï', 'Rhum brun, rhum blanc, Cointreau, sirop d''orgeat, jus de citron vert', '16 €', 5, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les incontournables', 'Caïpirinha', 'Cachaça, citron vert, sucre de canne', '11 €', 6, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les incontournables', 'Caïpiroska', 'Vodka Eristoff, citron vert, sucre de canne', '11 €', 7, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les incontournables', 'Long Island Ice Tea', 'Vodka, gin, rhum, tequila, triple sec, coca, jus de citron', '15 €', 8, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les mojitos', 'Classique', 'Rhum brun, citron vert, cassonade, menthe fraîche, eau gazeuse', '13 €', 9, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les mojitos', 'Royal', 'Rhum brun, citron vert, cassonade, menthe fraîche, champagne Laurent Perrier brut', '22 €', 10, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les mojitos', 'Fraise, Framboise ou Passion', 'Rhum blanc, citron vert, purée de fruit, menthe fraîche, eau gazeuse', '13 €', 11, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les mojitos', 'Myrte', 'Liqueur de myrte, citron vert, cassonade, menthe fraîche, eau gazeuse', '14 €', 12, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les spritz', 'Apérol', 'Apérol, prosecco, eau gazeuse, orange', '11 €', 13, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les spritz', 'Mattei', 'Cap Corse Mattei rouge, muscat pétillant Casanova, eau gazeuse, orange', '13 €', 14, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les spritz', 'Hugo', 'Liqueur Saint Germain, prosecco, eau gazeuse, menthe fraîche, citron', '16 €', 15, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les spritz', 'Limoncello', 'Limoncello, prosecco, eau gazeuse, citron', '13 €', 16, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les mules', 'Corsican', 'Gin Mattei, ginger beer, citron vert, cassonade', '14 €', 17, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les mules', 'Moscow', 'Vodka Eristoff, ginger beer, citron vert, cassonade', '13 €', 18, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les mules', 'Jamaïcan', 'Rhum ambré Havana, ginger beer, citron vert, cassonade', '13 €', 19, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les mules', 'Mexican', 'Tequila Olmeca, ginger beer, citron vert, cassonade', '14 €', 20, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les gin tonics', 'Bombay', 'Schweppes Tonic, baies de genièvre, citron jaune, citron vert', '13 €', 21, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les gin tonics', 'Mattei', 'Schweppes Tonic, baies de genièvre, citron jaune, citron vert', '16 €', 22, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les gin tonics', 'Hendrick''s', 'Schweppes Tonic, baies de genièvre, citron jaune, citron vert', '18 €', 23, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les cocktails sans alcool', 'Virgin Mojito', 'Citron vert, menthe fraîche, sucre de canne, limonade', '10 €', 24, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les cocktails sans alcool', 'Virgin Pina', 'Purée de coco, jus d''ananas, jus de citron', '10 €', 25, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les cocktails sans alcool', 'Virgin Mattei Spritz', 'Cap Mattei sans alcool, Muscat Casanova sans alcool', '14 €', 26, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les cocktails sans alcool', 'Afterglow', 'Grenadine, jus d''ananas, jus d''orange', '9 €', 27, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les cocktails d''après-dîner', 'Amaretto sour', 'Amaretto, blanc d''œuf, jus de citron, sirop de sucre', '14 €', 28, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les cocktails d''après-dîner', 'Pistacchio sour', 'Strato, blanc d''œuf, jus de citron, sirop de sucre', '14 €', 29, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les cocktails d''après-dîner', 'Irish coffee', 'Whisky, sirop de sucre, espresso, chantilly', '14 €', 30, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les cocktails d''après-dîner', 'Black Russian', 'Vodka, liqueur de café', '12 €', 31, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les cocktails d''après-dîner', 'Espresso Martini', 'Vodka, espresso, liqueur de café, sirop de sucre', '13 €', 32, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les cocktails d''après-dîner', 'Grasshopper', 'Crème de cacao blanc, crème de menthe, crème fraîche', '13 €', 33, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les cocktails d''après-dîner', 'Grog', 'Rhum brun, jus de citron, miel, anis étoilé, cannelle, eau chaude', '13 €', 34, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Whisky', 'Ballantine''s', 'Écosse', '8 €', 35, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Whisky', 'Jack Daniel''s n°7', 'USA', '12 €', 36, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Whisky', 'P&M Single Corn', 'Corse, France', '14 €', 37, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Whisky', 'P&M Single Malt tourbé', 'Corse, France', '18 €', 38, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Whisky', 'Chivas 18 ans', 'Écosse', '25 €', 39, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Whisky', 'Yamazaki 12 ans', 'Japon', '32 €', 40, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Cognac & Armagnac', 'Henessy VS', 'France', '16 €', 41, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Cognac & Armagnac', 'Tariquet VSOP', 'France', '16 €', 42, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Gin', 'Bombay Sapphire', 'Angleterre', '9 €', 43, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Gin', 'Citadelle', 'France', '10 €', 44, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Gin', 'Mattei', 'Corse, France', '12 €', 45, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Gin', 'Hendrick''s', 'Écosse', '14 €', 46, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Gin', 'Roku Sakura', 'Japon', '14 €', 47, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Gin', 'Monkey 47', 'Allemagne', '18 €', 48, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Vodka', 'Eristoff', 'Géorgie', '8 €', 49, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Vodka', 'Absolut', 'Suède', '12 €', 50, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Vodka', 'Belvedère', 'Pologne', '14 €', 51, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Rhum', 'Havana 3 ans', 'Cuba', '8 €', 52, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Rhum', 'Havana Especial', 'Cuba', '8 €', 53, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Rhum', 'Saison Spiced', 'Caraïbes', '8 €', 54, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Rhum', 'Don Papa', 'Philippines', '12 €', 55, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Rhum', 'Diplomatico', 'Vénézuéla', '14 €', 56, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Rhum', 'Eminente', 'Cuba', '18 €', 57, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Rhum', 'Appleton Black 15 ans', 'Jamaïque', '18 €', 58, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Rhum', 'Planteray PXXO', 'La Barbade', '22 €', 59, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Tequila · Jalisco, Mexique', 'Olmeca blanco', NULL, '9 €', 60, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Tequila · Jalisco, Mexique', 'Casamigos Reposado', NULL, '18 €', 61, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Tequila · Jalisco, Mexique', 'Patron Silver', NULL, '20 €', 62, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Tequila · Jalisco, Mexique', 'Clase Azul Reposado', NULL, '40 €', 63, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Tequila · Jalisco, Mexique', 'Adiccion Anejo', NULL, '45 €', 64, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Tequila · Jalisco, Mexique', 'Don Julio 1942', NULL, '52 €', 65, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Mezcal · Oaxaca, Mexique', 'San Cosme', NULL, '12 €', 66, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Mezcal · Oaxaca, Mexique', 'Adiccion', NULL, '40 €', 67, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Eaux de vie & liqueurs', 'Grappa, Myrte', NULL, '8 €', 68, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Eaux de vie & liqueurs', 'Prune', NULL, '9 €', 69, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Eaux de vie & liqueurs', 'Get 27, Get 31, Jagermeister, Bailey''s, Malibu, Cointreau, Café', NULL, '8 €', 70, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Eaux de vie & liqueurs', 'Italicus', 'Bergamote', '12 €', 71, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Eaux de vie & liqueurs', 'Amaretto Disaronno, Myrte blanche', NULL, '9 €', 72, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Eaux de vie & liqueurs', 'Limoncello, Myrte rouge', NULL, '6 €', 73, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Eaux de vie & liqueurs', 'Châtaigne, Cedra', NULL, '8 €', 74, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Eaux de vie & liqueurs', 'Noisette', NULL, '10 €', 75, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Eaux de vie & liqueurs', 'Prunelle de Bourgogne, Poire, Abricot, Mandarine, Cerise, Framboise, Cassis, Verveine', NULL, '12 €', 76, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les apéritifs', 'Ricard, Casanis, 51', NULL, '4 €', 77, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les apéritifs', 'Martini, Cap Corse, Porto', NULL, '6 €', 78, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les apéritifs', 'Campari', NULL, '8 €', 79, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les apéritifs', 'Muscat, Muscat pétillant, Prosecco', NULL, '7 €', 80, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les apéritifs', 'Kir', 'Cassis, mûre, framboise, pêche, fraise', '9 €', 81, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les bières', 'Heineken, 25 cl', NULL, '4,50 €', 82, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les bières', 'Pietra, 33 cl', 'Ambrée, Rossa, Limoncella', '7 €', 83, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les bières', 'Paolina, 33 cl', 'Blonde, Blanche à l''immortelle, Miel', '7 €', 84, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les bières', 'Desperados, 33 cl', NULL, '7 €', 85, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les bières', 'Pression Pietra Bionda, 25 cl', NULL, '5 €', 86, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les bières', 'Pression Pietra Bionda, 50 cl', NULL, '9 €', 87, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (0, 'Les bières', 'Panaché, Monaco, Tango, Gommé, 25 cl', NULL, '5,50 €', 88, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Coté bar, à partager', 'Planche de charcuterie du fils Bucchini', NULL, '19 €', 1, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Coté bar, à partager', 'Planche de Prizuttu', NULL, '22 €', 2, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Coté bar, à partager', 'Planche de fromages', 'Confiture de figues', '19 €', 3, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Coté bar, à partager', 'La grande planche mixte', 'Charcuterie & fromages', '36 €', 4, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Coté bar, à partager', 'Antipasti de légumes à la braise', 'Mozzarella di buffala, huile d''olive', '17 €', 5, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Coté bar, à partager', 'Les croques truffés', NULL, '24 €', 6, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Coté bar, à partager', 'Pimientos del Padron', 'Fleur de sel, huile d''olive', '15 €', 7, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Coté bar, à partager', 'Houmous Libanais', 'Pois chiches frits, huile aux herbes et tortillas', '18 €', 8, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Coté bar, à partager', 'Nachos au cheddar', 'Chips de maïs, cheddar, jalapenos, olives noires, viande hachée à la tomate, crème d''Isigny', '22 €', 9, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Les entrées', 'Planche de charcuterie du fils Bucchini', NULL, '19 €', 10, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Les entrées', 'Assiette de Prizuttu', NULL, '22 €', 11, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Les entrées', 'Tomates, burrata crémeuse', 'Huile basilic et toasts grillés', '18 €', 12, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Les entrées', 'Salade Grecque', 'Tomates, concombres, feta, oignons rouges, olives noires, origan', '15 €', 13, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Les entrées', 'Antipasti de légumes à la braise', 'Mozzarella di buffala, huile d''olive', '17 €', 14, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Les entrées', 'Carpaccio de poulpe', 'Vinaigrette acidulée, noisettes', '25 €', 15, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Les entrées', 'La vraie Caesar', 'Romaine, poulet, croutons, œuf mollet, parmesan, sauce à l''anchois', '18 €', 16, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Les entrées', 'Avocado toast', 'Pain toasté, avocat, œuf mollet, fromage frais, sésame', '18 €', 17, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Les entrées', 'Carpaccio de bœuf', 'Fleurs de câpres, citron, parmesan, champignons frais, huile d''olive', '16 €', 18, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (1, 'Les entrées', 'Os à moelle braisé', 'Pain grillé à l''ail', '15 €', 19, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (2, 'Les pâtes', 'Lasagnes', NULL, '19 €', 1, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (2, 'Les pâtes', 'Linguine Tomates Burrata', 'Pignons grillés, roquette', '19 €', 2, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (2, 'Les pâtes', 'Linguine Saumon', NULL, '21 €', 3, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (2, 'Les pâtes', 'Linguine Crème de Truffe', 'Jambon en chiffonnade et parmesan', '22 €', 4, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (2, 'Les pâtes', 'Linguine Bottarga', 'Œufs de mulet séchés, huile d''olive, ail, persil, piment', '28 €', 5, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (2, 'Les classiques', 'Cheese Burger', 'Steak Black Angus, pain, cheddar, tomate, salade, confit d''oignons, sauce burger', '18 €', 6, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (2, 'Les classiques', 'Tartare de bœuf au couteau', 'Bavette Allemande, échalotes, câpres, cornichons, persil, émietté de fêta, croutons noirs, œuf, sauce', '24 €', 7, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (2, 'Les classiques', 'Grande escalope de veau panée au corn flakes', NULL, '24 €', 8, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (2, 'Les enfants · jusqu''à 11 ans', 'Poulet pané frites, linguine au jambon ou Pizzetta au fromage', NULL, '13 €', 9, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (3, 'La braise', 'Entrecôte', 'Origine UE, 400 g env., frites', '35 €', 1, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (3, 'La braise', 'Cotelettes d''agneau', 'Origine UE, pommes de terre grenailles', '29 €', 2, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (3, 'La braise', 'Daurade ou Loup entier', 'Selon arrivage, 300/400 g', '26 €', 3, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (3, 'La braise', 'Filet de Saumon fumé au bois de cerisier', NULL, '27 €', 4, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (3, 'La braise', 'Trio de gambas sauvages', 'Beurre d''ail, zeste de citron, persil frais', '32 €', 5, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (3, 'La braise', 'Poulpe, Gambas et gremolata', NULL, '29 €', 6, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (3, 'La braise', 'Poulpe grillé laqué au miel & paprika fumé', 'Crème de chorizo', '35 €', 7, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (3, 'Suppléments', 'Riz pilaf', NULL, '5 €', 8, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (3, 'Suppléments', 'Salade verte', NULL, '4 €', 9, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (3, 'Suppléments', 'Frites', NULL, '4 €', 10, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (3, 'Suppléments', 'Pommes de terre grenailles', NULL, '4 €', 11, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (3, 'Suppléments', 'Sucrine braisée', NULL, '5 €', 12, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (3, 'Suppléments', 'Avocat braisé, sauce yaourt', NULL, '6 €', 13, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (3, 'Suppléments', 'Poêlée de légumes', NULL, '7 €', 14, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (3, 'Suppléments', 'Sauces : poivre, roquefort, chimichurri', NULL, '3 €', 15, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Pane Pizza', 'Sel, huile d''olive, romarin', '9 €', 1, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Margherita', 'Tomate, fior di latte', '14 €', 2, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Napolitana', 'Tomate, fior di latte, anchois, olives noires, origan', '14,50 €', 3, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Prosciutto', 'Tomate, fior di latte, jambon', '15 €', 4, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Calzone', 'Tomate, fior di latte, jambon, champignons frais', '16 €', 5, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Regina', 'Tomate, fior di latte, jambon, champignons frais', '16 €', 6, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Regina bianca', 'Crème, fior di latte, jambon, champignons frais', '16 €', 7, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Chèvre miel', 'Crème, fior di latte, fromage de chèvre, miel', '16 €', 8, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Oignons Rock', 'Tomate, fior di latte, oignons confits, roquefort', '16 €', 9, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', '4 Formaggi', 'Tomate, fior di latte, emmental, gorgonzola, parmigiano', '17 €', 10, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Isula', 'Tomate, fior di latte, saucisse sarde, oignons, olives noires, origan', '17 €', 11, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Vegetariana', 'Tomate, fior di latte, courgettes, aubergines, parmesan, basilic, huile d''olive', '17 €', 12, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Baciata di Romy', 'Roquette, jambon de parme, tomates fraîches, stracciatella, huile d''olive (garnie après cuisson)', '17 €', 13, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Pepperoni', 'Tomate, fior di latte, poivrons, chorizo, gorgonzola', '17,50 €', 14, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Parma', 'Tomate, fior di latte, jambon de parme, roquette, parmesan', '17,50 €', 15, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Capricciosa', 'Tomate, fior di latte, jambon, artichauts, champignons frais, olives, parmesan', '17,50 €', 16, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Estiva', 'Tomate, fior di latte, tomates cerises, stracciatella, roquette', '17,50 €', 17, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Golfo', 'Tomate, fior di latte, jambon, saucisse sarde piquante, oignons, œuf, origan', '18 €', 18, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Burrata', 'Tomate, fior di latte, roquette, burrata', '19 €', 19, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Les pizze au feu de bois', 'Tartufata', 'Crème, fior di latte, crème de truffe noire, parmesan, roquette', '20 €', 20, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Suppléments pizze', 'Fromage, œuf, anchois, légume', NULL, '2 €', 21, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Suppléments pizze', 'Jambon, saucisse, parme, sauce truffe', NULL, '4 €', 22, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (4, 'Suppléments pizze', 'Stracciatella, burrata', NULL, '6 €', 23, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Le fromage', 'Planche de fromages, confiture de figues', 'À partager', '19 €', 1, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les desserts', 'Affogato', NULL, '7 €', 2, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les desserts', 'Tiramisu traditionnel', NULL, '11 €', 3, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les desserts', 'Soupe de fraises à la fleur d''oranger', 'Sorbet mangue, chantilly maison', '14 €', 4, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les desserts', 'Mousse au chocolat', NULL, '10 €', 5, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les desserts', 'Moelleux à la châtaigne', 'Glace artisanale à la châtaigne', '9 €', 6, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les desserts', 'Crème brûlée à la vanille', NULL, '9 €', 7, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les desserts', 'Fiadone', NULL, '11 €', 8, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les desserts', 'Dessert du jour', NULL, '9 €', 9, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les coupes glacées', 'Banana split', 'Vanille, fraise, chocolat, banane fraîche, chantilly, amandes effilées, sauce chocolat', '15 €', 10, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les coupes glacées', 'Chocolat Liégeois', '2 boules chocolat, lait chocolaté, chantilly, sauce chocolat', '12 €', 11, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les coupes glacées', 'Café Liégeois', '2 boules café, café frappé, chantilly, sauce café', '12 €', 12, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les coupes glacées', 'Caramellata', 'Vanille, caramel beurre salé, chantilly, amandes effilées, sauce caramel', '12 €', 13, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les coupes glacées', 'Bounty', 'Chocolat, noix de coco, chantilly, sauce chocolat, brisures de bounty', '12 €', 14, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les coupes glacées', 'Cookie & cream', 'Vanille, chocolat, cookie dough, chantilly, sauce chocolat, brisures de cookies', '15 €', 15, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les coupes glacées', 'Castagniccia', 'Vanille, 2 boules châtaigne, confiture de châtaignes corses, chantilly', '15 €', 16, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les coupes glacées', 'Spéculoos', 'Vanille, 2 boules spéculoos, brisures de spéculoos, chantilly, sauce spéculoos', '15 €', 17, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les coupes glacées', 'Dame Blanche', '3 boules vanille, chantilly & beaucoup de sauce chocolat', '15 €', 18, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les coupes glacées', 'Colonel', '2 boules citron, vodka, zeste de citron vert', '12 €', 19, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les coupes glacées', 'Sicilienne', 'Mangue, fraise, framboise, pago fraise, chantilly, sauce fruits rouges, amandes effilées', '16 €', 20, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les coupes glacées', 'Choco Dubaï', 'Chocolat, 2 boules pistache, chantilly, sauce pistache', '15 €', 21, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les coupes glacées', 'Le Milkshake', 'Parfum au choix, chantilly', '10 €', 22, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les glaces artisanales', 'La boule', NULL, '4 €', 23, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les glaces artisanales', 'Chantilly maison', NULL, '2 €', 24, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les glaces artisanales', 'Topping', NULL, '1,50 €', 25, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (5, 'Les glaces artisanales', 'Sauce', NULL, '1 €', 26, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'La sélection au verre', 'Cuvée classique', 'Rouge, blanc, rosé', '7 €', 1, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'La sélection au verre', 'Cuvée supérieure', 'Rouge, blanc, rosé', '10 €', 2, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'La sélection au verre', 'Myrtus, domaine Sant''Armettu', 'Sartène, rouge', '16 €', 3, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'La sélection au verre', 'Myrtus, domaine Sant''Armettu', 'Sartène, blanc', '18 €', 4, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'La sélection au verre', 'Cantinone, domaine Vico', 'Morosaglia, rouge', '18 €', 5, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'La sélection au verre', 'Clos Nicrosi', 'Rogliano, blanc', '15 €', 6, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'La sélection au verre', 'Champagne Laurent Perrier brut réserve', NULL, '18 €', 7, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rosés', 'Villa Rossa', 'IGP Corse', '28 €', 8, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rosés', 'Aria, domaine Zuria', 'Bonifacio', '36 €', 9, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rosés', 'Clos Landry, gris rose', 'Calvi', '38 €', 10, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rosés', 'Gris de Pauline, domaine Marquiliani', 'Aleria · Magnum 80', '39 €', 11, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rosés', 'Initiale, domaine Zuria', 'Bonifacio', '46 €', 12, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rosés', 'Clos Venturi', 'Ponte Leccia', '49 €', 13, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rosés', 'Domaine Vaccelli', 'Ajaccio', '60 €', 14, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les blancs', 'Villa Rossa', 'IGP Corse', '28 €', 15, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les blancs', 'Cuvée Valle, Castellu Piattu', 'Patrimonio', '38 €', 16, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les blancs', 'Albore, Nicolas Mariotti Bindi', 'Patrimonio', '40 €', 17, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les blancs', 'Domaine Camellu', 'Calvi', '42 €', 18, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les blancs', 'Clos Nicrosi', 'Rogliano', '51 €', 19, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les blancs', 'Domaine Leccia', 'Patrimonio', '59 €', 20, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les blancs', 'Myrtus, domaine Sant''Armettu', 'Sartène', '65 €', 21, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les blancs', 'Crocci, domaine Zuria', 'Bonifacio', '110 €', 22, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les blancs', 'Tarra di Sognu, Clos Canarelli', 'Figari', '110 €', 23, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rouges', 'Villa Rossa', 'IGP Corse', '28 €', 24, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rouges', 'E Petre', 'Côte Orientale', '32 €', 25, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rouges', 'Costa Rossa, Daniel Canarelli', 'Figari', '39 €', 26, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rouges', 'Cuvée des Gouverneurs, Orenga de Gaffory', 'Patrimonio', '48 €', 27, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rouges', 'Storia di Corni Mozzi, Clos Culombu', 'Calvi', '52 €', 28, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rouges', 'Sempre Azzezzu, domaine Giacometti', 'Patrimonio', '55 €', 29, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rouges', 'Myrtus, domaine Sant''Armettu', 'Sartène', '60 €', 30, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rouges', 'Réserve perpétuelle, Castellu di Baricci', 'Sartène', '65 €', 31, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rouges', 'Cantinone, domaine Vico', 'Calvi', '75 €', 32, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rouges', 'La chapelle, Castellu d''Alba', 'Haute-Corse', '85 €', 33, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rouges', 'Porcellese Non Solus, Nicolas Mariotti Bindi', 'Patrimonio', '90 €', 34, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rouges', 'Clos Signadore', 'Patrimonio', '130 €', 35, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les rouges', 'Stintinu, domaine Zuria', 'Bonifacio', '140 €', 36, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les champagnes', 'Laurent Perrier brut réserve', NULL, '90 €', 37, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les champagnes', 'Billecart Salmon brut', NULL, '100 €', 38, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les champagnes', 'Billecart Salmon rosé', NULL, '150 €', 39, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les vins de dessert', 'Muscat', 'Corse, 12 cl', '7 €', 40, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les vins de dessert', 'Vino Santo de Toscane', 'Italie, 12 cl', '12 €', 41, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (6, 'Les vins de dessert', 'Vin de Constance', '2022, Klein Constantia, Afrique du Sud, 12 cl', '45 €', 42, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les softs', 'Sirop à l''eau', NULL, '3 €', 1, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les softs', 'Limonade', NULL, '4 €', 2, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les softs', 'Coca, Coca Zéro', NULL, '4 €', 3, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les softs', 'Orangina, Liptonic, Oasis, Ice Tea', NULL, '4 €', 4, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les softs', 'Pago', 'Tomate, fraise, orange, ACE, ananas, pomme', '4 €', 5, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les softs', 'Schweppes Tonic, Agrumes', NULL, '4 €', 6, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les softs', 'Redbull', NULL, '6 €', 7, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les softs', 'Redbull pastèque', NULL, '6 €', 8, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les softs', 'Ginger beer', NULL, '5 €', 9, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les softs', 'Orange, Citron pressé', NULL, '6 €', 10, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les softs', 'Thé glacé maison', NULL, '7 €', 11, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les softs', 'Agua Fresca concombre citron vert', 'Détox', '7 €', 12, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les boissons chaudes', 'Espresso, Décaféiné', NULL, '3 €', 13, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les boissons chaudes', 'Macchiato', NULL, '3,50 €', 14, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les boissons chaudes', 'Chocolat chaud', NULL, '5 €', 15, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les boissons chaudes', 'Chocolat viennois', NULL, '6 €', 16, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les boissons chaudes', 'Grand crème, Cappuccino', NULL, '5 €', 17, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les boissons chaudes', 'Lait chaud ou froid', NULL, '3 €', 18, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les boissons chaudes', 'Café frappé', NULL, '5 €', 19, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les boissons chaudes', 'Café Latte', 'Vanille, caramel, chocolat', '6 €', 20, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les boissons chaudes', 'Café Latte frappé', 'Vanille, caramel, chocolat', '6 €', 21, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les boissons chaudes', 'Avoine Latte', 'Vanille, caramel ou chocolat', '7 €', 22, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (7, 'Les boissons chaudes', 'Sélection de thés et infusions Kusmi Tea', NULL, '4 €', 23, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (8, 'Tous les jours de 8h à 11h', 'Le petit déjeuner complet', 'Café ou thé, jus de fruit, 1 viennoiserie, pain beurre et confiture · autre boisson chaude +2', '9,50 €', 1, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (8, 'Tous les jours de 8h à 11h', 'Viennoiserie', 'Pain au chocolat ou croissant', '2 €', 2, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (8, 'Tous les jours de 8h à 11h', 'Pain beurre & confiture', NULL, '3 €', 3, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (8, 'Tous les jours de 8h à 11h', 'Skyr', NULL, '5 €', 4, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (8, 'Vendredi, samedi & dimanche de 8h30 à 11h', 'Œufs brouillés crémeux, pain toasté', 'Supp. cheddar +2 · supp. jambon blanc, bacon, sauce à la truffe +4', '10 €', 5, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (8, 'Vendredi, samedi & dimanche de 8h30 à 11h', 'Œufs au plat, bacon, pain toasté', NULL, '12 €', 6, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (8, 'Vendredi, samedi & dimanche de 8h30 à 11h', 'Omelette nature', NULL, '9 €', 7, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (8, 'Vendredi, samedi & dimanche de 8h30 à 11h', 'Omelette jambon', NULL, '13 €', 8, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (8, 'Vendredi, samedi & dimanche de 8h30 à 11h', 'Omelette jambon fromage', NULL, '15 €', 9, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (8, 'Vendredi, samedi & dimanche de 8h30 à 11h', 'Avocado toast', 'Pain toasté, avocat, fromage frais, œuf mollet, sésame', '18 €', 10, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (8, 'Vendredi, samedi & dimanche de 8h30 à 11h', 'Toast Italien', 'Pain toasté, jambon de parme, stracciatella, tomates cerises, parmesan, pignons grillés', '18 €', 11, 1);
INSERT INTO carte (panel, categorie, nom, descr, prix, ordre, visible) VALUES (8, 'Vendredi, samedi & dimanche de 8h30 à 11h', 'Supplément avocat', NULL, '6 €', 12, 1);
